# -*- coding: utf-8 -*-
"""Anagram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t_qai218ha0GWcLe4kRX03eQhXTsJ7AF
"""

class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:

        maps = {}
        for i in range(0,len(strs)):
            str1 = strs[i]
            primeprod = self.primeProduct(str1)
            if primeprod not in maps:
                maps[primeprod] = []
            maps[primeprod].append(str1)

        return maps.values()
        
    
    def primeProduct(self, s):
        primes = [2, 3, 5, 7, 11 ,13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 107]
        result = 1
        for i in range(0,len(s)):
            c = s[i]
            result = result*primes[ord(c)-ord('a')]
        return result