# -*- coding: utf-8 -*-
"""Isomorphic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uWBi0dJrF05EFAghLJ4ZGDDNgMZmPRyp
"""

class Solution:
    def isIsomorphic(self, s: str, t: str) -> bool:
        zipped_set = set(zip(s, t))
        return len(zipped_set) == len(set(s)) == len(set(t))