# -*- coding: utf-8 -*-
"""#13(leetcode - 205)IsomorphicStrings .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jaS1gaJk4mS6tF_vj0Zmf8HAktTu4-pL
"""

class Solution:
    def isIsomorphic(self, s: str, t: str) -> bool:
        
        un = {}
        un1 = {}

        for x in range(len(s)):
           
            if ( s[x] in un):
                if (un[s[x]] != t[x] ):

                    return False
            else:
                un[s[x]] = t[x]

            if (t[x] in un1 ):
                if (un1[t[x]] != s[x]):
                    return False
            else:
                un1[t[x]] = s[x]


        return True


#TC : O(n)
#SC = O(n) ##{O(n) + O(n) = O(2n) = O(n)}