# -*- coding: utf-8 -*-
"""WordPattern.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12H4X0nWr2F8wqKbHpdocoms-KTA9AXP0
"""

class Solution:
    def wordPattern(self, pattern: str, s: str) -> bool:
        strList = s.split(" ")
        if (len(pattern) != len(strList)): return False
        
        cMap = {}
        sSet = set()
        
        for i in range(len(pattern)):
            _str = strList[i]
            _char = pattern[i]
            if(_char in cMap):
                if(cMap.get(_char) != _str):
                    return False
            else:
                if(_str in sSet):
                    return False
                cMap[_char] = _str
                sSet.add(_str)
        
        return True